server:
  port: 9002

spring:
  application:
    name: mock-exam-service

  datasource:
    url: jdbc:postgresql://localhost:5432/mock-exam
    username: mock-exam
    password: mockexampassword

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    defer-datasource-initialization: true

  main:
    allow-circular-references: true

jwt:
  key: "secret"
  expire: 64000000000

